package org.vr.di;

/**
 * Created by vladimirrybkin on 01/11/16.
 */

public interface DiNames {

    String APPLICATION_COMPONENT = "APPLICATION_COMPONENT";
    String BOOTSTRAP_COMPONENT = "BOOTSTRAP_COMPONENT";
    String ACTIVITY_COMPONENT = "ACTIVITY_COMPONENT";
    String ROUTER_COMPONENT = "ROUTER_COMPONENT";
    String ROOT_SCREEN_COMPONENT = "ROOT_SCREEN_COMPONENT";

}
